/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 * Run `bun run generate:api` to regenerate from the backend OpenAPI spec.
 *
 * Note: This is a manually created placeholder based on backend schemas.
 * Regenerate from running backend for production use.
 */

export interface paths {
	'/api/v1/invitations': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List invitations with pagination, filtering, and sorting */
		get: operations['list_invitations'];
		put?: never;
		/** Create a new invitation */
		post: operations['create_invitation'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/invitations/{invitation_id}': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				invitation_id: string;
			};
			cookie?: never;
		};
		/** Get invitation details */
		get: operations['get_invitation'];
		put?: never;
		post?: never;
		/** Delete an invitation */
		delete: operations['delete_invitation'];
		options?: never;
		head?: never;
		/** Update an invitation */
		patch: operations['update_invitation'];
		trace?: never;
	};
	'/api/v1/invitations/validate/{code}': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				code: string;
			};
			cookie?: never;
		};
		/** Validate an invitation code */
		get: operations['validate_invitation'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/users': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List users with pagination, filtering, and sorting */
		get: operations['list_users'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/users/{user_id}': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				user_id: string;
			};
			cookie?: never;
		};
		/** Get user details */
		get: operations['get_user'];
		put?: never;
		post?: never;
		/** Delete a user */
		delete: operations['delete_user'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/users/{user_id}/enable': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				user_id: string;
			};
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Enable a user */
		post: operations['enable_user'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/users/{user_id}/disable': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				user_id: string;
			};
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Disable a user */
		post: operations['disable_user'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/servers': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List all media servers with their libraries */
		get: operations['list_servers'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/servers/{server_id}/sync': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				server_id: string;
			};
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Sync users with media server */
		post: operations['sync_server'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/join/{code}': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				code: string;
			};
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Redeem an invitation */
		post: operations['redeem_invitation'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/join/plex/oauth/pin': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create Plex OAuth PIN */
		post: operations['create_plex_pin'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/join/plex/oauth/pin/{pin_id}': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				pin_id: number;
			};
			cookie?: never;
		};
		/** Check Plex OAuth PIN status */
		get: operations['check_plex_pin'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Health check */
		get: operations['health_check'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}

export type webhooks = Record<string, never>;

export interface components {
	schemas: {
		/** Standard error response */
		ErrorResponse: {
			detail: string;
			error_code: string;
			timestamp: string;
			correlation_id?: string | null;
		};
		/** Field-level validation error */
		FieldError: {
			field: string;
			messages: string[];
		};
		/** Validation error response with field details */
		ValidationErrorResponse: {
			detail: string;
			error_code: string;
			timestamp: string;
			correlation_id?: string | null;
			field_errors: components['schemas']['FieldError'][];
		};
		/** Media server response */
		MediaServerResponse: {
			id: string;
			name: string;
			server_type: 'jellyfin' | 'plex';
			url: string;
			enabled: boolean;
			created_at: string;
			updated_at?: string | null;
		};
		/** Library response */
		LibraryResponse: {
			id: string;
			name: string;
			library_type: string;
			external_id: string;
			created_at: string;
			updated_at?: string | null;
		};
		/** Media server with libraries response */
		MediaServerWithLibrariesResponse: {
			id: string;
			name: string;
			server_type: 'jellyfin' | 'plex';
			url: string;
			enabled: boolean;
			created_at: string;
			libraries: components['schemas']['LibraryResponse'][];
			updated_at?: string | null;
		};
		/** Create invitation request */
		CreateInvitationRequest: {
			server_ids: string[];
			code?: string | null;
			expires_at?: string | null;
			max_uses?: number | null;
			duration_days?: number | null;
			library_ids?: string[] | null;
			permissions?: Record<string, boolean> | null;
		};
		/** Update invitation request */
		UpdateInvitationRequest: {
			expires_at?: string | null;
			max_uses?: number | null;
			duration_days?: number | null;
			enabled?: boolean | null;
			server_ids?: string[] | null;
			library_ids?: string[] | null;
			permissions?: Record<string, boolean> | null;
		};
		/** Invitation response */
		InvitationResponse: {
			id: string;
			code: string;
			use_count: number;
			enabled: boolean;
			created_at: string;
			expires_at?: string | null;
			max_uses?: number | null;
			duration_days?: number | null;
			created_by?: string | null;
			updated_at?: string | null;
			is_active: boolean;
			remaining_uses?: number | null;
		};
		/** Invitation detail response with relationships */
		InvitationDetailResponse: {
			id: string;
			code: string;
			use_count: number;
			enabled: boolean;
			created_at: string;
			target_servers: components['schemas']['MediaServerResponse'][];
			allowed_libraries: components['schemas']['LibraryResponse'][];
			expires_at?: string | null;
			max_uses?: number | null;
			duration_days?: number | null;
			created_by?: string | null;
			updated_at?: string | null;
			is_active: boolean;
			remaining_uses?: number | null;
		};
		/** Paginated invitation list response */
		InvitationListResponse: {
			items: components['schemas']['InvitationResponse'][];
			total: number;
			page: number;
			page_size: number;
			has_next: boolean;
		};
		/** Invitation validation response */
		InvitationValidationResponse: {
			valid: boolean;
			failure_reason?: string | null;
			target_servers?: components['schemas']['MediaServerResponse'][] | null;
			allowed_libraries?: components['schemas']['LibraryResponse'][] | null;
			duration_days?: number | null;
		};
		/** Redeem invitation request */
		RedeemInvitationRequest: {
			username: string;
			password: string;
			email?: string | null;
		};
		/** Identity response */
		IdentityResponse: {
			id: string;
			display_name: string;
			enabled: boolean;
			created_at: string;
			email?: string | null;
			expires_at?: string | null;
			updated_at?: string | null;
		};
		/** User response */
		UserResponse: {
			id: string;
			identity_id: string;
			media_server_id: string;
			external_user_id: string;
			username: string;
			enabled: boolean;
			created_at: string;
			expires_at?: string | null;
			updated_at?: string | null;
		};
		/** User detail response with relationships */
		UserDetailResponse: {
			id: string;
			identity_id: string;
			media_server_id: string;
			external_user_id: string;
			username: string;
			enabled: boolean;
			created_at: string;
			identity: components['schemas']['IdentityResponse'];
			media_server: components['schemas']['MediaServerResponse'];
			expires_at?: string | null;
			updated_at?: string | null;
			invitation_id?: string | null;
			invitation?: components['schemas']['InvitationResponse'] | null;
		};
		/** Paginated user list response */
		UserListResponse: {
			items: components['schemas']['UserDetailResponse'][];
			total: number;
			page: number;
			page_size: number;
			has_next: boolean;
		};
		/** Redemption response */
		RedemptionResponse: {
			success: boolean;
			identity_id: string;
			users_created: components['schemas']['UserResponse'][];
			message?: string | null;
		};
		/** Redemption error response */
		RedemptionErrorResponse: {
			success: boolean;
			error_code: string;
			message: string;
			failed_server?: string | null;
			partial_users?: components['schemas']['UserResponse'][] | null;
		};
		/** Sync request */
		SyncRequest: {
			dry_run?: boolean;
		};
		/** Sync result */
		SyncResult: {
			server_id: string;
			server_name: string;
			synced_at: string;
			orphaned_users: string[];
			stale_users: string[];
			matched_users: number;
		};
		/** Plex OAuth PIN response */
		PlexOAuthPinResponse: {
			pin_id: number;
			code: string;
			auth_url: string;
			expires_at: string;
		};
		/** Plex OAuth check response */
		PlexOAuthCheckResponse: {
			authenticated: boolean;
			email?: string | null;
			error?: string | null;
		};
		/** Health check response */
		HealthCheckResponse: {
			status: string;
			checks: Record<string, boolean>;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}

export type $defs = Record<string, never>;

export interface operations {
	list_invitations: {
		parameters: {
			query?: {
				page?: number;
				page_size?: number;
				enabled?: boolean;
				expired?: boolean;
				sort_by?: 'created_at' | 'expires_at' | 'use_count';
				sort_order?: 'asc' | 'desc';
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['InvitationListResponse'];
				};
			};
		};
	};
	create_invitation: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateInvitationRequest'];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['InvitationDetailResponse'];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ValidationErrorResponse'];
				};
			};
		};
	};
	get_invitation: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				invitation_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['InvitationDetailResponse'];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	update_invitation: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				invitation_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateInvitationRequest'];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['InvitationDetailResponse'];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ValidationErrorResponse'];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	delete_invitation: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				invitation_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	validate_invitation: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				code: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['InvitationValidationResponse'];
				};
			};
		};
	};
	list_users: {
		parameters: {
			query?: {
				page?: number;
				page_size?: number;
				server_id?: string;
				invitation_id?: string;
				enabled?: boolean;
				expired?: boolean;
				sort_by?: 'created_at' | 'username' | 'expires_at';
				sort_order?: 'asc' | 'desc';
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['UserListResponse'];
				};
			};
		};
	};
	get_user: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				user_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['UserDetailResponse'];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	enable_user: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				user_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['UserDetailResponse'];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	disable_user: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				user_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['UserDetailResponse'];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	delete_user: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				user_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	sync_server: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				server_id: string;
			};
			cookie?: never;
		};
		requestBody?: {
			content: {
				'application/json': components['schemas']['SyncRequest'];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SyncResult'];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			503: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	list_servers: {
		parameters: {
			query?: {
				enabled?: boolean;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['MediaServerWithLibrariesResponse'][];
				};
			};
		};
	};
	redeem_invitation: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				code: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RedeemInvitationRequest'];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json':
						| components['schemas']['RedemptionResponse']
						| components['schemas']['RedemptionErrorResponse'];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['RedemptionErrorResponse'];
				};
			};
		};
	};
	create_plex_pin: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PlexOAuthPinResponse'];
				};
			};
		};
	};
	check_plex_pin: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				pin_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PlexOAuthCheckResponse'];
				};
			};
		};
	};
	health_check: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HealthCheckResponse'];
				};
			};
		};
	};
}
