/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/v1/invitations': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List invitations
		 * @description List invitations with pagination, filtering, and sorting.
		 */
		get: operations['ApiV1InvitationsListInvitations'];
		put?: never;
		/**
		 * Create invitation
		 * @description Create a new invitation with configurable settings.
		 */
		post: operations['ApiV1InvitationsCreateInvitation'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/invitations/{invitation_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get invitation details
		 * @description Retrieve complete details for a specific invitation.
		 */
		get: operations['ApiV1InvitationsInvitationIdGetInvitation'];
		put?: never;
		post?: never;
		/**
		 * Delete invitation
		 * @description Delete an invitation without affecting users created from it.
		 */
		delete: operations['ApiV1InvitationsInvitationIdDeleteInvitation'];
		options?: never;
		head?: never;
		/**
		 * Update invitation
		 * @description Update mutable fields of an invitation.
		 */
		patch: operations['ApiV1InvitationsInvitationIdUpdateInvitation'];
		trace?: never;
	};
	'/api/v1/invitations/validate/{code}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Validate invitation code
		 * @description Validate an invitation code without redeeming it. Public endpoint.
		 */
		get: operations['ApiV1InvitationsValidateCodeValidateInvitation'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/join/{code}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Redeem invitation
		 * @description Redeem an invitation code to create user accounts on target media servers.
		 */
		post: operations['ApiV1JoinCodeRedeemInvitation'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/join/plex/oauth/pin/{pin_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Check Plex OAuth PIN status
		 * @description Check if a PIN has been authenticated. Returns the user's email if authentication is complete.
		 */
		get: operations['ApiV1JoinPlexOauthPinPinIdCheckPin'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/join/plex/oauth/pin': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Create Plex OAuth PIN
		 * @description Generate a PIN for Plex OAuth authentication. The user should be directed to the auth_url to complete authentication.
		 */
		post: operations['ApiV1JoinPlexOauthPinCreatePin'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/servers': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List media servers
		 * @description List all media servers with their libraries.
		 */
		get: operations['ApiV1ServersListServers'];
		put?: never;
		/**
		 * Create media server
		 * @description Add a new media server with connection validation.
		 */
		post: operations['ApiV1ServersCreateServer'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/servers/{server_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get media server
		 * @description Retrieve details for a specific media server.
		 */
		get: operations['ApiV1ServersServerIdGetServer'];
		put?: never;
		post?: never;
		/**
		 * Delete media server
		 * @description Remove a media server and all associated data.
		 */
		delete: operations['ApiV1ServersServerIdDeleteServer'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/servers/{server_id}/sync': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Sync users with media server
		 * @description Synchronize local user records with the actual state of users on the media server.
		 */
		post: operations['ApiV1ServersServerIdSyncSyncServer'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/users/{user_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get user details
		 * @description Retrieve complete details for a specific user.
		 */
		get: operations['ApiV1UsersUserIdGetUser'];
		put?: never;
		post?: never;
		/**
		 * Delete user
		 * @description Delete a user from both local database and media server.
		 */
		delete: operations['ApiV1UsersUserIdDeleteUser'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/users/{user_id}/disable': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Disable user
		 * @description Disable a user account on both local database and media server.
		 */
		post: operations['ApiV1UsersUserIdDisableDisableUser'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/users/{user_id}/enable': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Enable user
		 * @description Enable a user account on both local database and media server.
		 */
		post: operations['ApiV1UsersUserIdEnableEnableUser'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/users': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List users
		 * @description List users with pagination, filtering, and sorting.
		 */
		get: operations['ApiV1UsersListUsers'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/users/{user_id}/permissions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/**
		 * Update user permissions
		 * @description Update user permissions on the media server.
		 */
		patch: operations['ApiV1UsersUserIdPermissionsUpdatePermissions'];
		trace?: never;
	};
	'/api/v1/wizards/{wizard_id}/steps': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Create step
		 * @description Create a new step in a wizard.
		 */
		post: operations['ApiV1WizardsWizardIdStepsCreateStep'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/wizards': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List wizards
		 * @description List wizards with pagination and filtering.
		 */
		get: operations['ApiV1WizardsListWizards'];
		put?: never;
		/**
		 * Create wizard
		 * @description Create a new wizard with configurable settings.
		 */
		post: operations['ApiV1WizardsCreateWizard'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/wizards/{wizard_id}/steps/{step_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Delete step
		 * @description Delete a wizard step and normalize remaining step orders.
		 */
		delete: operations['ApiV1WizardsWizardIdStepsStepIdDeleteStep'];
		options?: never;
		head?: never;
		/**
		 * Update step
		 * @description Update mutable fields of a wizard step.
		 */
		patch: operations['ApiV1WizardsWizardIdStepsStepIdUpdateStep'];
		trace?: never;
	};
	'/api/v1/wizards/{wizard_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get wizard details
		 * @description Retrieve complete details for a wizard including all steps.
		 */
		get: operations['ApiV1WizardsWizardIdGetWizard'];
		put?: never;
		post?: never;
		/**
		 * Delete wizard
		 * @description Delete a wizard and all its steps.
		 */
		delete: operations['ApiV1WizardsWizardIdDeleteWizard'];
		options?: never;
		head?: never;
		/**
		 * Update wizard
		 * @description Update mutable fields of a wizard.
		 */
		patch: operations['ApiV1WizardsWizardIdUpdateWizard'];
		trace?: never;
	};
	'/api/v1/wizards/{wizard_id}/steps/{step_id}/reorder': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Reorder step
		 * @description Move a step to a new position in the wizard.
		 */
		post: operations['ApiV1WizardsWizardIdStepsStepIdReorderReorderStep'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/wizards/validate-step': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Validate step completion
		 * @description Validate a step completion response. Public endpoint.
		 */
		post: operations['ApiV1WizardsValidateStepValidateStep'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** CreateInvitationRequest */
		CreateInvitationRequest: {
			server_ids: string[];
			code?: string | null;
			expires_at?: string | null;
			max_uses?: number | null;
			duration_days?: number | null;
			library_ids?: string[] | null;
			permissions?: {
				[key: string]: boolean;
			} | null;
			pre_wizard_id?: string | null;
			post_wizard_id?: string | null;
		};
		/** IdentityResponse */
		IdentityResponse: {
			/** Format: uuid */
			id: string;
			display_name: string;
			enabled: boolean;
			/** Format: date-time */
			created_at: string;
			email?: string | null;
			expires_at?: string | null;
			updated_at?: string | null;
		};
		/** InvitationDetailResponse */
		InvitationDetailResponse: {
			/** Format: uuid */
			id: string;
			code: string;
			use_count: number;
			enabled: boolean;
			/** Format: date-time */
			created_at: string;
			target_servers: components['schemas']['MediaServerResponse'][];
			allowed_libraries: components['schemas']['LibraryResponse'][];
			expires_at?: string | null;
			max_uses?: number | null;
			duration_days?: number | null;
			created_by?: string | null;
			updated_at?: string | null;
			/** @default true */
			is_active: boolean;
			remaining_uses?: number | null;
			pre_wizard?: components['schemas']['WizardResponse'] | null;
			post_wizard?: components['schemas']['WizardResponse'] | null;
		};
		/** InvitationListResponse */
		InvitationListResponse: {
			items: components['schemas']['InvitationResponse'][];
			total: number;
			page: number;
			page_size: number;
			has_next: boolean;
		};
		/** InvitationResponse */
		InvitationResponse: {
			/** Format: uuid */
			id: string;
			code: string;
			use_count: number;
			enabled: boolean;
			/** Format: date-time */
			created_at: string;
			expires_at?: string | null;
			max_uses?: number | null;
			duration_days?: number | null;
			created_by?: string | null;
			updated_at?: string | null;
			/** @default true */
			is_active: boolean;
			remaining_uses?: number | null;
		};
		/** InvitationValidationResponse */
		InvitationValidationResponse: {
			valid: boolean;
			failure_reason?: string | null;
			target_servers?: components['schemas']['MediaServerResponse'][] | null;
			allowed_libraries?: components['schemas']['LibraryResponse'][] | null;
			duration_days?: number | null;
			pre_wizard?: components['schemas']['WizardDetailResponse'] | null;
			post_wizard?: components['schemas']['WizardDetailResponse'] | null;
		};
		/** LibraryResponse */
		LibraryResponse: {
			/** Format: uuid */
			id: string;
			name: string;
			library_type: string;
			external_id: string;
			/** Format: date-time */
			created_at: string;
			updated_at?: string | null;
		};
		/** MediaServerCreate */
		MediaServerCreate: {
			name: string;
			server_type: string;
			url: string;
			api_key: string;
		};
		/** MediaServerResponse */
		MediaServerResponse: {
			/** Format: uuid */
			id: string;
			name: string;
			server_type: string;
			url: string;
			enabled: boolean;
			/** Format: date-time */
			created_at: string;
			updated_at?: string | null;
		};
		/** MediaServerWithLibrariesResponse */
		MediaServerWithLibrariesResponse: {
			/** Format: uuid */
			id: string;
			name: string;
			server_type: string;
			url: string;
			enabled: boolean;
			/** Format: date-time */
			created_at: string;
			libraries: components['schemas']['LibraryResponse'][];
			updated_at?: string | null;
		};
		/** PlexOAuthCheckResponse */
		PlexOAuthCheckResponse: {
			authenticated: boolean;
			email?: string | null;
			error?: string | null;
		};
		/** PlexOAuthPinResponse */
		PlexOAuthPinResponse: {
			pin_id: number;
			code: string;
			auth_url: string;
			/** Format: date-time */
			expires_at: string;
		};
		/** RedeemInvitationRequest */
		RedeemInvitationRequest: {
			username: string;
			password: string;
			email?: string | null;
		};
		/** RedemptionErrorResponse */
		RedemptionErrorResponse: {
			/** @default false */
			success: boolean;
			error_code: string;
			message: string;
			failed_server?: string | null;
			partial_users?: components['schemas']['UserResponse'][] | null;
		};
		/** RedemptionResponse */
		RedemptionResponse: {
			success: boolean;
			/** Format: uuid */
			identity_id: string;
			users_created: components['schemas']['UserResponse'][];
			message?: string | null;
		};
		/** StepReorderRequest */
		StepReorderRequest: {
			new_order: number;
		};
		/** StepValidationRequest */
		StepValidationRequest: {
			/** Format: uuid */
			step_id: string;
			response: {
				[key: string]: string | number | boolean | null;
			};
			started_at?: string | null;
		};
		/** StepValidationResponse */
		StepValidationResponse: {
			valid: boolean;
			completion_token?: string | null;
			error?: string | null;
		};
		/** SyncRequest */
		SyncRequest: {
			/** @default true */
			dry_run: boolean;
		};
		/** UpdateInvitationRequest */
		UpdateInvitationRequest: {
			expires_at?: string | null;
			max_uses?: number | null;
			duration_days?: number | null;
			enabled?: boolean | null;
			server_ids?: string[] | null;
			library_ids?: string[] | null;
			permissions?: {
				[key: string]: boolean;
			} | null;
			pre_wizard_id?: string | null;
			post_wizard_id?: string | null;
		};
		/** UpdatePermissionsRequest */
		UpdatePermissionsRequest: {
			can_download?: boolean | null;
			can_stream?: boolean | null;
			can_sync?: boolean | null;
			can_transcode?: boolean | null;
		};
		/** UserDetailResponse */
		UserDetailResponse: {
			/** Format: uuid */
			id: string;
			/** Format: uuid */
			identity_id: string;
			/** Format: uuid */
			media_server_id: string;
			external_user_id: string;
			username: string;
			enabled: boolean;
			/** Format: date-time */
			created_at: string;
			identity: components['schemas']['IdentityResponse'];
			media_server: components['schemas']['MediaServerResponse'];
			expires_at?: string | null;
			updated_at?: string | null;
			invitation_id?: string | null;
			invitation?: components['schemas']['InvitationResponse'] | null;
		};
		/** UserListResponse */
		UserListResponse: {
			items: components['schemas']['UserDetailResponse'][];
			total: number;
			page: number;
			page_size: number;
			has_next: boolean;
		};
		/** UserResponse */
		UserResponse: {
			/** Format: uuid */
			id: string;
			/** Format: uuid */
			identity_id: string;
			/** Format: uuid */
			media_server_id: string;
			external_user_id: string;
			username: string;
			enabled: boolean;
			/** Format: date-time */
			created_at: string;
			expires_at?: string | null;
			updated_at?: string | null;
		};
		/** WizardCreate */
		WizardCreate: {
			name: string;
			description?: string | null;
			/** @default true */
			enabled: boolean;
		};
		/** WizardDetailResponse */
		WizardDetailResponse: {
			/** Format: uuid */
			id: string;
			name: string;
			enabled: boolean;
			/** Format: date-time */
			created_at: string;
			steps: components['schemas']['WizardStepResponse'][];
			description?: string | null;
			updated_at?: string | null;
		};
		/** WizardListResponse */
		WizardListResponse: {
			items: components['schemas']['WizardResponse'][];
			total: number;
			page: number;
			page_size: number;
			has_next: boolean;
		};
		/** WizardResponse */
		WizardResponse: {
			/** Format: uuid */
			id: string;
			name: string;
			enabled: boolean;
			/** Format: date-time */
			created_at: string;
			description?: string | null;
			updated_at?: string | null;
		};
		/** WizardStepCreate */
		WizardStepCreate: {
			interaction_type: string;
			title: string;
			content_markdown: string;
			config?: {
				[key: string]: string | number | boolean | string[] | null;
			};
			step_order?: number | null;
		};
		/** WizardStepResponse */
		WizardStepResponse: {
			/** Format: uuid */
			id: string;
			/** Format: uuid */
			wizard_id: string;
			step_order: number;
			interaction_type: string;
			title: string;
			content_markdown: string;
			config: {
				[key: string]: string | number | boolean | string[] | null;
			};
			/** Format: date-time */
			created_at: string;
			updated_at?: string | null;
		};
		/** WizardStepUpdate */
		WizardStepUpdate: {
			title?: string | null;
			content_markdown?: string | null;
			config?: {
				[key: string]: string | number | boolean | string[] | null;
			} | null;
		};
		/** WizardUpdate */
		WizardUpdate: {
			name?: string | null;
			description?: string | null;
			enabled?: boolean | null;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	ApiV1InvitationsListInvitations: {
		parameters: {
			query?: {
				/** @description Page number (1-indexed) */
				page?: number;
				/** @description Number of items per page (max 100) */
				page_size?: number;
				/** @description Filter by enabled status */
				enabled?: boolean | null;
				/** @description Filter by expiration status */
				expired?: boolean | null;
				/** @description Field to sort by (created_at, expires_at, use_count) */
				sort_by?: string;
				/** @description Sort order (asc, desc) */
				sort_order?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['InvitationListResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1InvitationsCreateInvitation: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateInvitationRequest'];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['InvitationDetailResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1InvitationsInvitationIdGetInvitation: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Invitation UUID */
				invitation_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['InvitationDetailResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1InvitationsInvitationIdDeleteInvitation: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Invitation UUID */
				invitation_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, nothing follows */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1InvitationsInvitationIdUpdateInvitation: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Invitation UUID */
				invitation_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateInvitationRequest'];
			};
		};
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['InvitationDetailResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1InvitationsValidateCodeValidateInvitation: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Invitation code to validate */
				code: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['InvitationValidationResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1JoinCodeRedeemInvitation: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Invitation code to redeem */
				code: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RedeemInvitationRequest'];
			};
		};
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json':
						| components['schemas']['RedemptionResponse']
						| components['schemas']['RedemptionErrorResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1JoinPlexOauthPinPinIdCheckPin: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description PIN ID to check */
				pin_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PlexOAuthCheckResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1JoinPlexOauthPinCreatePin: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PlexOAuthPinResponse'];
				};
			};
		};
	};
	ApiV1ServersListServers: {
		parameters: {
			query?: {
				/** @description Filter by enabled status */
				enabled?: boolean | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['MediaServerWithLibrariesResponse'][];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1ServersCreateServer: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['MediaServerCreate'];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['MediaServerResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1ServersServerIdGetServer: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Media server UUID */
				server_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['MediaServerResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1ServersServerIdDeleteServer: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Media server UUID */
				server_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, nothing follows */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1ServersServerIdSyncSyncServer: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Media server UUID */
				server_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['SyncRequest'];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1UsersUserIdGetUser: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description User UUID */
				user_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['UserDetailResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1UsersUserIdDeleteUser: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description User UUID */
				user_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, nothing follows */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1UsersUserIdDisableDisableUser: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description User UUID */
				user_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['UserDetailResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1UsersUserIdEnableEnableUser: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description User UUID */
				user_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['UserDetailResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1UsersListUsers: {
		parameters: {
			query?: {
				/** @description Page number (1-indexed) */
				page?: number;
				/** @description Number of items per page (default 50, max 100) */
				page_size?: number;
				/** @description Filter by media server ID */
				server_id?: string | null;
				/** @description Filter by invitation ID */
				invitation_id?: string | null;
				/** @description Filter by enabled status */
				enabled?: boolean | null;
				/** @description Filter by expiration status */
				expired?: boolean | null;
				/** @description Field to sort by (created_at, username, expires_at) */
				sort_by?: string;
				/** @description Sort order (asc, desc) */
				sort_order?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['UserListResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1UsersUserIdPermissionsUpdatePermissions: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description User UUID */
				user_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdatePermissionsRequest'];
			};
		};
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['UserDetailResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1WizardsWizardIdStepsCreateStep: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Wizard UUID */
				wizard_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['WizardStepCreate'];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WizardStepResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1WizardsListWizards: {
		parameters: {
			query?: {
				/** @description Page number (1-indexed) */
				page?: number;
				/** @description Number of items per page (max 100) */
				page_size?: number;
				/** @description Filter by enabled status */
				enabled?: boolean | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WizardListResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1WizardsCreateWizard: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['WizardCreate'];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WizardResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1WizardsWizardIdStepsStepIdDeleteStep: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Wizard UUID */
				wizard_id: string;
				/** @description Step UUID */
				step_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, nothing follows */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1WizardsWizardIdStepsStepIdUpdateStep: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Wizard UUID */
				wizard_id: string;
				/** @description Step UUID */
				step_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['WizardStepUpdate'];
			};
		};
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WizardStepResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1WizardsWizardIdGetWizard: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Wizard UUID */
				wizard_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WizardDetailResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1WizardsWizardIdDeleteWizard: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Wizard UUID */
				wizard_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, nothing follows */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1WizardsWizardIdUpdateWizard: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Wizard UUID */
				wizard_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['WizardUpdate'];
			};
		};
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WizardResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1WizardsWizardIdStepsStepIdReorderReorderStep: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Wizard UUID */
				wizard_id: string;
				/** @description Step UUID */
				step_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['StepReorderRequest'];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WizardStepResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1WizardsValidateStepValidateStep: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['StepValidationRequest'];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['StepValidationResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
}
