<script lang="ts">
/**
 * Main log viewer container.
 *
 * Manages SSE lifecycle, filtering, pause/resume, and auto-scroll behavior.
 * Connects on mount, disconnects on cleanup.
 */

import { ArrowDown, ScrollText } from "@lucide/svelte";
import EmptyState from "$lib/components/empty-state.svelte";
import { Button } from "$lib/components/ui/button";
import { Skeleton } from "$lib/components/ui/skeleton";
import {
	clearEntries,
	connect,
	disconnect,
	getConnected,
	getEntries,
	getError,
	getLoading,
	LEVEL_ORDER,
	type LogEntry,
	type LogLevel,
} from "$lib/stores/log-stream.svelte";
import LogEntryRow from "./log-entry.svelte";
import LogToolbar from "./log-toolbar.svelte";

// Filter state
let levelFilter = $state("ALL");
let sourceFilter = $state("");
let searchQuery = $state("");

// Pause state
let paused = $state(false);
let pausedEntries = $state.raw<LogEntry[]>([]);

// Auto-scroll state
let autoScroll = $state(true);
let scrollContainer: HTMLDivElement | undefined = $state();

// Reactive getters
const entries = $derived(getEntries());
const connected = $derived(getConnected());
const loading = $derived(getLoading());
const error = $derived(getError());

// Snapshot entries when paused
const displayEntries = $derived(paused ? pausedEntries : entries);

// Filtered entries
const filteredEntries = $derived.by(() => {
	let result = displayEntries;

	if (levelFilter !== "ALL") {
		const minLevel = LEVEL_ORDER[levelFilter as LogLevel] ?? 0;
		result = result.filter((e) => (LEVEL_ORDER[e.level] ?? 0) >= minLevel);
	}

	if (sourceFilter) {
		const src = sourceFilter.toLowerCase();
		result = result.filter((e) => e.logger_name.toLowerCase().includes(src));
	}

	if (searchQuery) {
		const q = searchQuery.toLowerCase();
		result = result.filter(
			(e) =>
				e.message.toLowerCase().includes(q) ||
				e.logger_name.toLowerCase().includes(q) ||
				Object.values(e.fields).some((v) => v.toLowerCase().includes(q)),
		);
	}

	return result;
});

const totalCount = $derived(displayEntries.length);

// Auto-scroll when new entries arrive
$effect(() => {
	// Track dependency on filtered entries length
	filteredEntries.length;

	if (autoScroll && scrollContainer) {
		requestAnimationFrame(() => {
			if (scrollContainer) {
				scrollContainer.scrollTop = scrollContainer.scrollHeight;
			}
		});
	}
});

// Connect on mount, disconnect on cleanup
$effect(() => {
	connect();
	return () => disconnect();
});

function handleScroll() {
	if (!scrollContainer) return;
	const { scrollTop, scrollHeight, clientHeight } = scrollContainer;
	autoScroll = scrollHeight - scrollTop - clientHeight < 50;
}

function jumpToLatest() {
	if (scrollContainer) {
		scrollContainer.scrollTop = scrollContainer.scrollHeight;
		autoScroll = true;
	}
}

function togglePause() {
	if (paused) {
		paused = false;
	} else {
		pausedEntries = entries;
		paused = true;
	}
}
</script>

<div class="flex flex-col gap-3">
	<LogToolbar
		{levelFilter}
		{sourceFilter}
		{searchQuery}
		entryCount={filteredEntries.length}
		{totalCount}
		{connected}
		{loading}
		{paused}
		{error}
		onLevelChange={(v) => (levelFilter = v)}
		onSourceChange={(v) => (sourceFilter = v)}
		onSearchChange={(v) => (searchQuery = v)}
		onClear={clearEntries}
		onTogglePause={togglePause}
	/>

	<!-- Scroll container -->
	<div class="relative">
		<div
			bind:this={scrollContainer}
			onscroll={handleScroll}
			class="h-[calc(100vh-13rem)] overflow-y-auto rounded-md border border-cr-border bg-cr-bg-card"
		>
			{#if loading}
				<div class="space-y-1 p-2">
					{#each Array(8) as _}
						<Skeleton class="h-7 w-full" />
					{/each}
				</div>
			{:else if filteredEntries.length === 0}
				{#if displayEntries.length === 0}
					<EmptyState
						title="No log entries yet"
						description="Log entries will appear here as they are generated by the backend."
						class="h-full border-none"
					>
						{#snippet icon()}
							<ScrollText class="size-8" />
						{/snippet}
					</EmptyState>
				{:else}
					<EmptyState
						title="No matching entries"
						description="Try adjusting your filters or search query."
						class="h-full border-none"
					>
						{#snippet icon()}
							<ScrollText class="size-8" />
						{/snippet}
					</EmptyState>
				{/if}
			{:else}
				{#each filteredEntries as entry (entry.seq)}
					<LogEntryRow {entry} />
				{/each}
			{/if}
		</div>

		<!-- Jump to latest button -->
		{#if !autoScroll && !paused}
			<div class="absolute bottom-3 left-1/2 -translate-x-1/2">
				<Button
					variant="secondary"
					size="sm"
					onclick={jumpToLatest}
					class="gap-1.5 shadow-md"
				>
					<ArrowDown class="size-3.5" />
					Jump to latest
				</Button>
			</div>
		{/if}
	</div>
</div>
