"""add sync_exclusions table

Revision ID: 4dc4ed3ab54b
Revises: 0004
Create Date: 2026-02-26 21:02:45.836689
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic.
revision: str = "4dc4ed3ab54b"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_exclusions",
        sa.Column("external_user_id", sa.String(length=255), nullable=False),
        sa.Column("media_server_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["media_server_id"],
            ["media_servers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sync_exclusions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sync_exclusions_external_user_id"),
            ["external_user_id"],
            unique=False,
        )
        batch_op.create_unique_constraint(
            "uq_sync_exclusions_external_user_server",
            ["external_user_id", "media_server_id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sync_exclusions", schema=None) as batch_op:
        batch_op.drop_constraint(
            "uq_sync_exclusions_external_user_server", type_="unique"
        )
        batch_op.drop_index(batch_op.f("ix_sync_exclusions_external_user_id"))

    op.drop_table("sync_exclusions")
    # ### end Alembic commands ###
