"""add totp fields to admin accounts

Revision ID: 6103f5e16ff6
Revises: 51d23bb57699
Create Date: 2026-02-28 17:42:31.713013
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic.
revision: str = "6103f5e16ff6"
down_revision: str | None = "51d23bb57699"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("admin_accounts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "totp_enabled",
                sa.Boolean(),
                nullable=False,
                server_default="0",
            )
        )
        batch_op.add_column(
            sa.Column("totp_secret_encrypted", sa.Text(), nullable=True)
        )
        batch_op.add_column(sa.Column("totp_backup_codes", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("admin_accounts", schema=None) as batch_op:
        batch_op.drop_column("totp_backup_codes")
        batch_op.drop_column("totp_secret_encrypted")
        batch_op.drop_column("totp_enabled")

    # ### end Alembic commands ###
